version: "3"

services:

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - S3_BUCKET=new-life-dev-s3
      - AWS_REGION=us-east-1
      - DB_HOST=database
      - DB_NAME=uploadsdb
      - DB_USER=admin
      - DB_PASSWORD=password
      
    depends_on:
      database:
        condition: service_healthy   # wait until database is healthy ✅

  database:
    image: postgres:15
    environment:
      - POSTGRES_DB=uploadsdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d uploadsdb"]
      interval: 5s     # check every 5 seconds
      timeout: 5s      # wait 5 seconds for response
      retries: 5       # try 5 times before giving up

volumes:
  postgres_data:          # data survives container restart ✅